GET http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json 

###

POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json 

{
    "id": 4,
    "titulo": "Aprende Python",
      "lenguaje": "python",
      "vistas": 15000,
      "nivel": "basico"
}

### 

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json 

{
    "id": 2,
    "titulo": "Python intermedio con proyectos",
      "lenguaje": "pythonnnnn",
      "vistas": 129822222277896,
      "nivel": "intermedio"
}

###

PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json 

{
    "titulo": "Pythssson CITssssO",
    "vistas": 1212342423432
}

###

DELETE http://localhost:3000/api/cursos/programacion/3 HTTP/1.1
Content-Type: application/json 
